export const courses = [
  {
    id: 1,
    title: "Solana Fundamentals",
    instructor: "Alex Johnson",
    students: 1248,
    duration: "8 hours",
    rating: 4.8,
    price: "$59",
    level: "Beginner",
    image: "/solana-network-flow.png",
  },
  {
    id: 2,
    title: "Smart Contract Development",
    instructor: "Maria Garcia",
    students: 864,
    duration: "12 hours",
    rating: 4.6,
    price: "$79",
    level: "Intermediate",
    image: "/interconnected-contracts.png",
  },
  {
    id: 3,
    title: "DeFi Applications",
    instructor: "James Wilson",
    students: 632,
    duration: "10 hours",
    rating: 4.7,
    price: "$69",
    level: "Advanced",
    image: "/interconnected-defi-network.png",
  },
  {
    id: 4,
    title: "NFT Marketplace Creation",
    instructor: "Sarah Ahmed",
    students: 1032,
    duration: "14 hours",
    rating: 4.9,
    price: "$89",
    level: "Intermediate",
    image: "/interconnected-defi-network.png",
    badge: "Bestseller",
  },
  {
    id: 5,
    title: "Solana Program Library",
    instructor: "Michael Chen",
    students: 428,
    duration: "6 hours",
    rating: 4.5,
    price: "$49",
    level: "Advanced",
    image: "/solana-network-flow.png",
  },
  {
    id: 6,
    title: "Web3 Security Fundamentals",
    instructor: "David Kim",
    students: 756,
    duration: "9 hours",
    rating: 4.7,
    price: "$69",
    level: "Intermediate",
    image: "/interconnected-contracts.png",
    badge: "New",
  },
  {
    id: 7,
    title: "Blockchain Interoperability",
    instructor: "Lisa Wang",
    students: 312,
    duration: "7 hours",
    rating: 4.4,
    price: "$59",
    level: "Advanced",
    image: "/interconnected-contracts.png",
  },
  {
    id: 8,
    title: "Tokenomics Design",
    instructor: "Robert Taylor",
    students: 524,
    duration: "5 hours",
    rating: 4.6,
    price: "$49",
    level: "Intermediate",
    image: "/interconnected-defi-network.png",
  },
  {
    id: 9,
    title: "Intro to Blockchain",
    instructor: "Emily Brown",
    students: 1876,
    duration: "4 hours",
    rating: 4.9,
    price: "$29",
    level: "Beginner",
    image: "/solana-network-flow.png",
    badge: "Popular",
  },
];
