import type { Metadata } from 'next'
import './globals.css'
import "@wallet-ui/tailwind/index.css";

import { AppProviders } from '@/components/app-providers'
import { AppLayout } from '@/components/app-layout'
import React from 'react'
import "@solana/wallet-adapter-react-ui/styles.css";

export const metadata: Metadata = {
  title: "Placeholder",
  description: "Generated by create-solana-dapp",
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <AppProviders>
          <AppLayout >
          
            {children}
           
            </AppLayout>
        </AppProviders>
      </body>
    </html>
  );
}
// Patch BigInt so we can log it using JSON.stringify without any errors
declare global {
  interface BigInt {
    toJSON(): string;
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString();
};
