import type { Metadata } from "next";
import "./globals.css";
import "@wallet-ui/tailwind/index.css";
import { AppProviders } from "@/components/app-providers";
import React from "react";
import "@solana/wallet-adapter-react-ui/styles.css";
import { Toaster } from "@/components/ui/sonner";
export const metadata: Metadata = {
  title: "Eduverse",
  description: "Generated by create-solana-dapp",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <AppProviders>{children}</AppProviders>
        <Toaster />
      </body>
    </html>
  );
}

declare global {
  interface BigInt {
    toJSON(): string;
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString();
};
